name: GSI Build

on: [push]

env:
  ROM_URL: https://aablzpjaephbx664cho5os3arznw6888.node.ppio.cloud:48106/fsa167af8c.a.bdydns.com/1435501072/Firmware/Flyme/meizu17/9.2.0.3/cn/20220424185818/498fa997/update.zip?f_ver=v1&max_age=7776000&r=MAIZRDl3aVoeBxRUT1MTJnYbCF0wOGgWFwNJf1FADDQ5BAgbDCE%2FGB1BC1xRSBRyb1lUGnhjdltLQQVXFwBRcWpGWQZ%2BfH5AQF9eFgwLWSU5T1QDZTg2ERkaAxdCWxE3BghaKSkoRBceA1dbVg9y&ppiouid=62b378c222ab8400011120dc741a5de8&ppio_auth=62b378c2__0_e6d3b5c95b469244f98a0f035198f163
  ROM_NAME: Flyme
  ZIP_NAME: Nusantara_v1
  TZ: America/Sao_Paulo
  MIR: gof
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x build/initial.sh
              . build/initial.sh

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'
 
       - name: Install python requirements
         run: |
              pip install pyrogram tgcrypto

       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/HitaloSama/ErfanGSIs.git

       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Copy and rename A-only build info
         run: cp ErfanGSIs/output/*Aonly*.txt Aonly.txt

       - name: Print A-Only build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt

       - name: Print AB build info
         run: |
              cat ErfanGSIs/output/*-AB-*.txt

       - name: Send build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}
         run: |
              python .github/workflows/robot.py
